language: go
go:
  - 1.8

script:
  - make all
  - make goveralls

before_deploy:
  - pip install --user release-manager==0.1.0

deploy:
  skip_cleanup: true
  provider: script
  script: make release
  on:
    condition: '"${TRAVIS_GO_VERSION}" == "1.8"' 
    tags: true

env:
  global:
  - secure: mY75DpkO4ELWVeHm2aOgusOenYj2lle4IVW8fZe9wnniwvfcluYrzU+zliiDtAEOC2DyN2RrcVI02QQxdhhFB5DGTpzs5R2fOCs1GZO+5uPcZKWrEAxB8JRhhEVcUkcRKQ8bMaKdD5A5/j6miWQISyLbpM0zBFpWyXmMq/Zc8FdYeVj55NusRBagXxvlh50r9WktG6ZXF+d8a3qFdrNOSB4EQnPcHjNDFza1Lt4sd4WF6ngTmiu0tEI7t1lDwK2i63P6Uw1OPHQqjxD2YZuhdhODruVHKy88afB1iqIukQJIYmCxYhCN2lQCY4/itqWGM6xkS7TSvmlovC+c7t9JULJO6sVtiLokco0VU/muENGbdHVTxk3n43MmPlDLA2I+nCFzZQze7KZAx7ILEIDepf23h1ok/b747B3wQWU5fYucIyikAFDhHXrC9fgxM/Np0iB4DiB0zN5RkNddk/+9K4Bgg6qWIfEix+YsEd8FEA1rNTfG6iN3le8nnJnk05kNMWaA0+wITg+22m0jx8mEv1hS9SvNTX3nq4MCw22DMzpd0FR6fUi8Dm2KDzfTcn78Axt2tZ3FVb7KgjM0JdgwotLBJuX1zv9QpFqkJBDkYinYJ4LP2wdekThNmZN4lOKatZaStn6dZGv30PfcZIWCwicxeQaJM5cWbOowVIa+dDA=
  - secure: nAefEhU/nOR8inyvOjoEOuScaYm6b4Iz9I7GfqcqSA4kd9JsyS6xlcGH/fNXFbkJ3x3uYV+dOebOlSYQpWIypRn8MI7qIq3kgDzUXYDY2PBowFhG49emslkaRbNA1jqMZdKYCUyL1+b4bZBWU9MaDKuajKFBXlivipuCdnmmHPKMYSH9WU/7Wgg0rOKpQNKIhdQfseIT6GhVwkg8X8siaW/mwljSwKLdPVUOaci3K8+v62NDe+dB7L1VCWt5F83YQGspCU+WdIH6QZ3nCGLuIL88gCH7zrMreb2FW2FGmcP2zV+zDmwclfc5cMxrrIytv1Z+fI9cFTdFn1DKywPxGXfcYb6tm9KI+U0fqcJ1wBl61+xBzvLD8Dci7u1tv9qX4TVIQcIBvzaeLKXpJhrwgj4zPvacmWFgdTrY3EX1r8z0BVq2wAfvJoo0iX9ZOhmJKRYwLS/GOhl13T1Yzs3j1LGzfKC2aPWTZhkBS4r5yCpQ0LHSETNC/Bg/Tdyw4pV240S0S9Q321zN+SP379LJbOoic/0g4g/AmvMU25Hcm12RWYh3wxUE5e8Sz9jTY4ciefOIYuXWMEm8+V0ZpEDGgGMKoUd1EO88i6JIzkcHwOl4J9dg2oWSAgWJKsA8+zZEWBsWpGE4BREeUlecXV+CK/LFP5KO+F8NKBld1r96LjE=
